# Generated by Django 4.2.2 on 2023-08-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("Gas Leak", "Gas Leak"),
                            ("Meter Reading", "Meter Reading"),
                        ],
                        max_length=20,
                    ),
                ),
                ("request_details", models.TextField()),
                ("attachment", models.FileField(upload_to="attachments/")),
                ("status", models.CharField(default="Pending", max_length=20)),
                (
                    "submitted_at",
                    models.CharField(default="08/12/2023, 23:58:39", max_length=20),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
