# Generated by Django 4.2.2 on 2023-08-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bynry_Gas_Company_Application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedatabase",
            name="submitted_at",
            field=models.DateTimeField(),
        ),
    ]
