# Generated by Django 4.2.2 on 2023-08-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bynry_Gas_Company_Application", "0002_alter_servicedatabase_submitted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedatabase",
            name="submitted_at",
            field=models.CharField(default="08/13/2023, 01:27:43", max_length=20),
        ),
    ]
