# Generated by Django 4.2.2 on 2023-08-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bynry_Gas_Company_Application", "0004_alter_servicedatabase_submitted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedatabase",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("Gas Leak", "Gas Leak"),
                    ("Meter Reading", "Meter Reading"),
                    ("Physical Damage", "Physical Damage"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="servicedatabase",
            name="submitted_at",
            field=models.CharField(default="08/13/2023, 01:41:25", max_length=20),
        ),
    ]
