# Generated by Django 4.2.2 on 2023-08-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Bynry_Gas_Company_Application",
            "0005_alter_servicedatabase_request_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedatabase",
            name="submitted_at",
            field=models.CharField(default="08/13/2023, 13:29:27", max_length=20),
        ),
    ]
